// category icons
import 'package:flutter/material.dart';

List<IconData> allCategoryIcons = [
  Icons.shopping_cart_outlined,
  Icons.restaurant_outlined,
  Icons.local_gas_station_rounded,
  Icons.home_rounded,
  Icons.directions_car_outlined,
  Icons.flight_outlined,
  Icons.medication_outlined,
  Icons.school_outlined,
  Icons.phone_android_outlined,
  Icons.computer_outlined,
  Icons.coffee_rounded,
  Icons.fitness_center_outlined,
  Icons.movie_outlined,
  Icons.videogame_asset_outlined,
  Icons.theater_comedy_outlined,
  Icons.music_note_outlined,
  Icons.pets_outlined,
  Icons.checkroom_outlined,
  Icons.spa_outlined,
  Icons.self_improvement_outlined,
  Icons.train_outlined,
  Icons.wine_bar_outlined,
  Icons.casino_outlined,
  Icons.celebration_outlined,
  Icons.bar_chart_outlined,
  Icons.lightbulb_outlined,
  Icons.devices_other_rounded,
  Icons.subscriptions_outlined,
  Icons.luggage_outlined,
  Icons.handyman_outlined,
  Icons.savings_outlined,
  Icons.atm_outlined,
  Icons.currency_bitcoin_outlined,
  Icons.work_outline_rounded,
  Icons.redeem_rounded,
  Icons.handshake_outlined,
  Icons.more_horiz_outlined,
  Icons.lunch_dining_rounded
];
